version: 2.1
# 2.3.0
orbs:
  snyk: snyk/snyk@2.3.0

jobs:
  snyk-code:
    docker:
      - image: cimg/node:24.0
    steps:
      - checkout
      - snyk/scan:
          command: code test
          monitor-on-build: false
          fail-on-issues: true

  snyk-open-source:
    docker:
      - image: cimg/node:24.0
    steps:
      - checkout
      - snyk/scan:
          command: test
          monitor-on-build: false
          fail-on-issues: true

workflows:
  snyk-scan:
    jobs:
      - snyk-code
      - snyk-open-source